### ISSUE TITLE
Rig Checklist & Risk Assessment

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#136]
Originally reported by: **David Taylor (BitBucket: [davidtaylorhq](http://bitbucket.org/davidtaylorhq), GitHub: [davidtaylorhq](http://github.com/davidtaylorhq))**

---

Digitise these. Need to be careful about database structure so data is not lost if form is changed in future

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/136

**Comment by johnathan99j** [comment]
CDM has now gone away, can this follow suit or do we still want to eventually digitise it all? There's also the current talk of how RA could become part of a checklist or be on RIGS entirely.

**Comment by samozzy** [comment]
I think there might want to be an amount of overlap. Whether that's small (pre-filled form to print out, checkboxes when it's complete), or significantly larger (complete transferal from a paper system to online), this requires much more consideration.

**Comment by FreneticScribbler** [comment]
This is probably better than using a note on the board for TODOs R.E. this...
TODO:
- [x] Automatic invalidation of review on editing like events and authorisations
- [ ] Proper permissions so that all keyholders can view (incl list), edit, etc - new H/S group to review
- [ ] Check UX consistency 
- [ ] Event Checklist:
	- [ ] Think about tickbox structure - Yes/No/N-A 
	- [ ] Backend for arbitrary numbers of vehicles and crew
- [ ] Graceful handling of old events
- [ ] Potential sharepoint linkage
